#workspace名字
workspace 'MySpace'

#静态库的名称
xcodeproj 'CommontLib/CommontLib.xcodeproj'

#实例工程名称
xcodeproj 'SpaceDemo/SpaceDemo.xcodeproj'


#静态库需要引入的三方库
target :CommontLib do
platform :ios, '8.0'
pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'MJExtension'
xcodeproj 'CommontLib/CommontLib.xcodeproj'
end


#实例工程需要引入的三方库
target :SpaceDemo do
platform :ios, '8.0'
pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'MJExtension'
xcodeproj 'SpaceDemo/SpaceDemo.xcodeproj'
end
