# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

workspace 'LibsDemo'


target 'TESTLIB' do
    xcodeproj '../LibsDemo/TESTLIB/TESTLIB.xcodeproj'
    pod 'JSONModel'
end

target 'HomeModlue' do
    xcodeproj '../LibsDemo/Modlue/HomeModlue/HomeModlue.xcodeproj'
    pod 'JSONModel'
end

target 'LibsDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LibsDemo


pod 'JSONModel'

  target 'LibsDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LibsDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

